In [5]:
import pandas as pd
scores = pd.read_parquet("../data/gold/scores.parquet")
scores.nlargest(50, "score")[[c for c in ["step","amount","score"] if c in scores.columns]]

      step      amount  score
39       1     9533.48    1.0
386      1  1277212.77    1.0
1423     1     7206.33    1.0
2050     1  1277212.77    1.0
2345     1     2806.00    1.0
2567     1      181.00    1.0
13229   10  2662734.59    1.0
15172   10     9217.19    1.0
23737   10  2662734.59    1.0
38702  100  1422963.14    1.0
38704  100  1422963.14    1.0
38705  101  2222544.00    1.0
38706  101   891944.51    1.0
38707  101   891944.51    1.0
38708  101  2388251.16    1.0
38712  101  2222544.00    1.0
38713  101  2388251.16    1.0
38718  102  1076739.91    1.0
38719  102   548335.12    1.0
38720  102   872199.82    1.0
38721  102   872199.82    1.0
38725  102  1076739.91    1.0
38726  102   656118.37    1.0
38730  103   639468.22    1.0
38732  103  1254092.10    1.0
38735  103   710385.55    1.0
38736  103  1254092.10    1.0
38737  104  1762680.47    1.0
38739  104   803794.53    1.0
38740  104   803794.53    1.0
38747  104  1762680.47    1.0
38749  104   655294.30    1.0
38751  105  2988103.30    1.0
38752  105  1457085.28    1.0
38753  105  1457085.28    1.0
38754  105  1767112.66    1.0
38755  105  2988103.30    1.0
38756  105   511379.90    1.0
38758  105   539087.79    1.0
38763  105  1767112.66    1.0
38768  105   511379.90    1.0
38770  106  1486955.35    1.0
38771  106     8999.56    1.0
38774  106     8999.56    1.0
38775  106  2708906.59    1.0
38777  106  1486955.35    1.0
38779  106  1409248.64    1.0
38780  106    71277.45    1.0
38783  106  1409248.64    1.0
38784  106  2708906.59    1.0